import logging
import os
import re
import time
from typing import Dict, List

import numpy as np

from spark_real.perception.detection_fusion import fusion_map_fields
from spark_real.perception.spark_perception import ObjectDetection
from spark_real.control import success_verifier
from spark_real.control.score_executor import ExecutionResult
from spark_real.control.safe_robot import SafeRobot, Obstacle
from spark_real.bt_label_resolver import LabelResolvingDetectionMap
from spark_real.bt_library import BTCacheMiss, BTMatch
from spark_real.planning import robointer_gate
from spark_real.routes import state as _routes_state
from spark_real.utils.env_flags import env_flag

logger = logging.getLogger(__name__)

# Plan-source values reported alongside every score, and recorded into the
# recorded-episode metadata so an episode's provenance is never ambiguous.
#   pin/exact/alias/normalized/similar -> served from the BT library
#   seed  -> served from a version-controlled configs/bt_seeds entry
#   llm   -> generated by the planner this run
CACHE_PLAN_SOURCES = frozenset({"pin", "exact", "alias", "normalized", "similar", "seed"})

# Env fallbacks, used when the config key is absent (pre-INTEGRATOR) or
# when running headless without a family yaml.
PLAN_MODE_ENV = "SPARK_BT_PLAN_MODE"

def _bt_frozen(pipeline) -> bool:
    """True when the BT library must contribute nothing and learn nothing.

    The no-adaptation control. Reads the config first, then the
    SPARK_BT_FROZEN env override so a benchmark arm can set it per-run
    without editing a config file.
    """
    if env_flag("SPARK_BT_FROZEN"):
        return True
    return bool(getattr(getattr(pipeline, "config", None), "bt_frozen", False))

LEGACY_DISABLE_LLM_ENV = "SPARK_DISABLE_LLM"

# Params of a `verify:` predicate that name a detection label. Must mirror
# control/success_predicates._LABEL_KEYS.
VERIFY_LABEL_KEYS = ("obj", "container", "surface", "base", "target")


def build_detection_details(detections) -> List[Dict]:
    """Per-detection facts handed to the planner alongside the image.

    Geometry is included so the planner can make the grasp-strategy call
    itself: an OBB angle on a soft or round object is meaningless, and
    ``confidence`` + ``obb_confidence`` are how that is visible. Optional
    fields are omitted when unset rather than defaulted, so a low value
    always means measured-and-low.
    """
    out: List[Dict] = []
    for d in detections or []:
        pos = getattr(d, "position_3d", None)
        detail: Dict = {
            "label": getattr(d, "label", None),
            "confidence": getattr(d, "confidence", None),
            "position_3d": pos.tolist() if isinstance(pos, np.ndarray) else pos,
        }
        ar = getattr(d, "aspect_ratio", None)
        if ar is not None:
            detail["aspect_ratio"] = round(float(ar), 3)
        minor = getattr(d, "obb_minor_m", None)
        if minor:
            detail["obb_minor_mm"] = round(float(minor) * 1000.0, 1)
        angle = getattr(d, "world_major_axis_rad", None)
        if angle is not None:
            detail["obb_angle_deg"] = round(float(np.degrees(float(angle))), 1)
        obb_conf = float(getattr(d, "obb_confidence", 0.0) or 0.0)
        if obb_conf > 0.0:
            detail["obb_confidence"] = round(obb_conf, 3)
        mask = getattr(d, "mask", None)
        area = getattr(d, "mask_area", None)
        if area and mask is not None and getattr(mask, "size", 0):
            detail["mask_area_frac"] = round(float(area) / float(mask.size), 5)
        cam = getattr(d, "camera", None)
        if cam:
            detail["camera"] = cam
        if getattr(d, "low_quality", False):
            detail["low_quality"] = True
        # The MASK-derived axis, alongside the world OBB above. The two fail in
        # opposite conditions: obb_angle/aspect_ratio come from the depth
        # cloud, which on a thin specular tool is the least trustworthy number
        # in the scene, while the silhouette is excellent. Showing both, plus
        # WHY the axis was refused, lets the planner pick an angle from a
        # measurement.
        plane_angle = getattr(d, "plane_orientation_angle", None)
        if plane_angle is not None and np.isfinite(float(plane_angle)):
            detail["mask_angle_deg"] = round(float(np.degrees(float(plane_angle))), 1)
        plane_ar = getattr(d, "plane_aspect_ratio", None)
        if plane_ar is not None and np.isfinite(float(plane_ar)):
            detail["mask_aspect_ratio"] = round(float(plane_ar), 2)
        if getattr(d, "ar_inflated", False):
            detail["depth_stretched_the_obb"] = True
        if getattr(d, "shape_round", False):
            detail["mask_is_round"] = True
        # Container geometry, so a placement can be reasoned about instead of
        # guessed (a 10.3 cm plushie lowered into a 4.2 cm bowl tips it; the
        # planner has to be told the bowl's depth).
        rim = getattr(d, "rim_z_m", None)
        interior = getattr(d, "interior_z_m", None)
        if rim is not None and interior is not None:
            try:
                detail["rim_z_m"] = round(float(rim), 3)
                detail["interior_z_m"] = round(float(interior), 3)
                detail["container_depth_cm"] = round(
                    (float(rim) - float(interior)) * 100.0, 1
                )
            except (TypeError, ValueError):
                pass
        attempts = int(getattr(d, "reprompt_attempts", 0) or 0)
        if attempts:
            detail["reprompt_attempts"] = attempts
        out.append(detail)
    return out


def verify_block_labels(score) -> set:
    """Every detection label the score's top-level ``verify:`` block needs.

    Predicate labels live OUTSIDE the tree, so the tree walks that harvest
    SAM3 prompts and validate plan labels miss them entirely. A cached run
    whose predicate names a label nobody prompted for abstains in every
    camera and reports `unverified` forever.
    """
    out = set()
    if not isinstance(score, dict):
        return out
    block = score.get("verify")
    if not isinstance(block, dict):
        return out
    for pred in block.get("all") or []:
        if not isinstance(pred, dict):
            continue
        for key in VERIFY_LABEL_KEYS:
            val = pred.get(key)
            if isinstance(val, str) and val.strip():
                out.add(val.strip())
    return out


# Plan, execute, and full run_task orchestration.
# Mixed into the pipeline class.
class ExecutionMixin:

    # RoboInter spatial-annotation extension. Class-level defaults because
    # this is a mixin with no __init__ of its own; `_last_robointer` holds the
    # per-run resolution records so a trace can show WHY a proposal was
    # applied or refused.
    ROBOINTER_ENV = robointer_gate.ROBOINTER_ENV
    _last_robointer = None

    def robointer_config(self) -> robointer_gate.RoboInterConfig:
        """Resolve the `planning.robointer` block, env last.

        Same resolution order as PerceptionMixin._fusion_settings: profile.raw
        when the server loaded an overlay, else the packaged
        configs/<family>_default.yaml, then $SPARK_ROBOINTER. Default OFF.
        """
        return robointer_gate.resolve_settings(
            getattr(self, "profile", None), getattr(self, "config", None)
        )

    def plan_mode(self) -> str:
        """
        Which plan source is currently allowed: ``auto``, ``cache_only`` or
        ``llm``.

        Precedence, highest first:
          1. the persisted library toggle (``/api/bt/toggle_cache``, stored
             in ``<library>/runtime_state.json`` so it survives a restart),
          2. the in-process ``state.use_cached_bt`` (older UI builds),
          3. ``config.bt_plan_mode``,
          4. ``SPARK_BT_PLAN_MODE`` / legacy ``SPARK_DISABLE_LLM=1``.
        """
        lib = self._bt_library
        if lib is not None and lib.use_cached_bt is not None:
            return "cache_only" if lib.use_cached_bt else "llm"
        try:
            if _routes_state.use_cached_bt is not None:
                return "cache_only" if _routes_state.use_cached_bt else "llm"
        except Exception:
            pass
        mode = getattr(self.config, "bt_plan_mode", None)
        if not mode:
            mode = os.environ.get(PLAN_MODE_ENV) or ""
        if not mode and os.environ.get(LEGACY_DISABLE_LLM_ENV, "0") == "1":
            mode = "cache_only"
        mode = str(mode).strip().lower() or "auto"
        if mode not in ("auto", "cache_only", "llm"):
            logger.warning("[plan] unknown plan mode %r; using 'auto'", mode)
            return "auto"
        return mode

    def resolve_cached_bt(self, instruction: str, require_cached=None):
        """
        Resolve ``instruction`` against the BT library without planning.

        Returns a ``BTMatch`` or None. Raises ``BTCacheMiss`` on a miss when
        strict cache-only mode is active, so a demo-collection run fails
        loudly instead of quietly minting a fresh Gemini plan nobody froze.

        Shared by ``plan()`` and by the detection-prompt harvest in
        ``run_task``, so both see exactly the same tree.
        """
        lib = self._bt_library
        if lib is None:
            return None
        mode = self.plan_mode()
        strict = (mode == "cache_only") if require_cached is None else require_cached
        if mode == "llm" and require_cached is None:
            return None

        # Legacy single-shot UI pin ("select this BT for the next execute").
        # Consumed here; the persisted per-task pin inside the library is
        # the durable mechanism and is NOT consumed.
        try:
            one_shot = _routes_state.pinned_bt_hash
        except Exception:
            one_shot = None
        if one_shot:
            try:
                _routes_state.pinned_bt_hash = None
            except Exception:
                pass
            entry = lib.get(one_shot)
            if entry is not None:
                logger.info(
                    "[plan] single-shot pin -> BT %s (%r)",
                    entry.hash,
                    entry.instruction,
                )
                return BTMatch(entry=entry, source="pin", similarity=1.0)
            logger.warning(
                "[plan] single-shot pinned hash %s is not in the library; "
                "falling through to the normal resolver",
                one_shot,
            )

        match = lib.resolve(instruction, require_cached=strict)
        if match is not None:
            source = "seed" if match.entry.seed and match.source != "pin" else match.source
            logger.info(
                "[plan] cache %s: BT %s (%r, success=%d fail=%d, sim=%.2f)",
                source,
                match.entry.hash,
                match.entry.instruction,
                match.entry.success,
                match.entry.fail,
                match.similarity,
            )
            match.source = source
        return match

    def plan(
        self,
        instruction: str,
        detections: List[ObjectDetection],
        scene_image=None,
        detection_details: list = None,
        temperature: float = None,
        scene_camera: str = None,
    ) -> Dict:
        """
        Generate a SPARK score from instruction and detections.

        ``scene_camera`` names the camera ``scene_image`` was taken with. It
        is only read by the RoboInter extension, which states each detection's
        observed 2D box to the planner: pixel coordinates from a different
        camera describe a different image, so detections from other views are
        skipped rather than stated in the wrong frame.

        Resolves the BT library first (pin -> exact -> near-exact ->
        similarity) and only calls the planner on a miss, unless
        ``plan_mode()`` says otherwise. The chosen source and entry hash are
        left on ``self._last_plan_source`` / ``self._last_bt_hash`` so the
        caller can record the run's provenance and bump the right entry
        without re-resolving.
        """
        self._last_plan_source = None
        self._last_bt_hash = None

        # An explicit sampling temperature is an explicit request for a NEW
        # sample: the /scores page generates alternative trees for the same
        # task that way. Serving the cache there would silently return the
        # tree the operator is trying to find an alternative to.
        if temperature is None:
            match = self.resolve_cached_bt(instruction)
            if match is not None:
                self._last_plan_source = match.source
                self._last_bt_hash = match.hash
                # Detached copy: execute() pops label_corrections off the
                # score, which would otherwise mutate the library entry.
                return match.score
        elif self.plan_mode() == "cache_only":
            raise BTCacheMiss(
                f"plan_mode=cache_only forbids the LLM, but planning "
                f"{instruction!r} at temperature={temperature} is a request "
                f"for a fresh sample. Clear cache-only mode first."
            )

        if self.plan_mode() == "cache_only":
            # resolve_cached_bt already raises in this mode; belt and braces
            # for a library that is None.
            raise BTCacheMiss(
                f"plan_mode=cache_only and no BT library is loaded, so "
                f"{instruction!r} cannot be planned without the LLM"
            )
        if self._planner is None:
            raise RuntimeError(
                f"no cached BT for {instruction!r} and no planner is "
                f"configured; seed a BT into the library first"
            )
        self._last_plan_source = "llm"

        labels = [d.label for d in detections]
        # Few-shot context: similarity-retrieved entries PLUS any
        # promoted ones (which are always included regardless of
        # jaccard similarity, so they act as canonical recipes).
        _bt_examples = []
        if self._bt_library is not None and not _bt_frozen(self):
            promoted = self._bt_library.promoted_entries()
            similar = self._bt_library.top_k_for(instruction, k=3)
            seen = {p[0] for p in promoted}
            _bt_examples = promoted + [s for s in similar if s[0] not in seen]

        logger.info(
            "[plan] cache MISS for %r (%d entries, floor=%.2f); calling the "
            "planner. This run's tree will be cached on success.",
            instruction,
            len(self._bt_library) if self._bt_library is not None else 0,
            (
                getattr(self._bt_library, "min_similarity", 0.0)
                if self._bt_library is not None
                else 0.0
            ),
        )

        # RoboInter (default OFF): let the planner answer with GEOMETRY, not
        # just a label. The image gains the 0..1000 grid its coordinates are
        # measured on, the prompt gains the schema plus every detection's
        # observed box in that same space, and the reply's `__robointer`
        # blocks are schema-checked on the way back. With the gate off,
        # `_ri_context` is None and every line below is a no-op.
        _ri = self.robointer_config()
        # scene_image may now be a list of (camera, image) views. RoboInter is
        # defined against exactly ONE camera -- its box space is that camera's
        # 0..1000 frame -- so it operates on the primary view only, and the
        # extra views ride along untouched for the planner to cross-check.
        _extra_views = []
        if isinstance(scene_image, (list, tuple)):
            _views_in = list(scene_image)
            if _views_in and isinstance(_views_in[0], (list, tuple)):
                _primary_cam, _primary_img = _views_in[0]
                scene_camera = scene_camera or _primary_cam
                _extra_views = _views_in[1:]
            else:
                _primary_img = _views_in[0] if _views_in else None
                _extra_views = [(scene_camera or "view", v) for v in _views_in[1:]]
            scene_image = _primary_img

        scene_image = robointer_gate.annotate_planner_image(_ri, scene_image)
        _ri_context = robointer_gate.planner_context(
            _ri, detections, scene_image, scene_camera
        )
        # Re-assemble after RoboInter has had its single-camera pass.
        if _extra_views:
            scene_image = [(scene_camera or "scene", scene_image)] + list(_extra_views)
        _bt_examples = robointer_gate.fewshot_examples(_ri) + _bt_examples

        # Per-run sampling override: the scores page generates BT variations
        # by re-planning at nonzero temperature. The planner default is
        # restored afterwards so normal runs stay deterministic.
        _old_temp = None
        if temperature is not None and self._planner is not None:
            _old_temp = self._planner.temperature
            self._planner.temperature = float(temperature)
        try:
            score = self._planner.generate_score(
                instruction=instruction,
                annotated_image=scene_image,
                scene_camera=scene_camera,
                keypoint_labels=labels,
                detection_details=detection_details,
                fewshot_examples=_bt_examples,
                robointer_context=_ri_context,
                robointer_strict=_ri.strict,
            )
            score = self._validate_plan_labels(
                score,
                labels,
                instruction,
                scene_image,
                detection_details,
                _bt_examples,
                robointer_context=_ri_context,
                robointer_strict=_ri.strict,
                scene_camera=scene_camera,
            )
        finally:
            if _old_temp is not None:
                self._planner.temperature = _old_temp
        return score

    def _validate_plan_labels(
        self,
        score,
        labels,
        instruction,
        scene_image,
        detection_details,
        fewshot,
        robointer_context=None,
        robointer_strict=False,
        scene_camera=None,
    ):
        """
        Refuse to return a BT that references labels nobody detected.

        Gemini is told to use the exact detected labels, but when the
        few-shot vocabulary diverges it can invent labels that only fail
        mid-run as 'not found in detections'. Collect every label the tree
        references, allow the detection labels plus label_corrections
        targets, re-prompt once with the exact valid set on mismatch, and
        raise rather than hand back an unexecutable plan.
        """
        label_keys = (
            "keypoint_label",
            "container_label",
            "target_label",
            "dustpan_label",
        )

        def used_labels(s):
            out = set()

            def walk(node):
                if not isinstance(node, dict):
                    return
                p = node.get("params") or {}
                for k in label_keys:
                    v = p.get(k)
                    if v:
                        out.add(str(v))
                for c in node.get("children") or []:
                    walk(c)

            walk(s.get("tree") if isinstance(s, dict) else None)
            # Predicate labels live outside the tree but must be detectable
            # too, or the run executes fine and then cannot be verified.
            out |= verify_block_labels(s)
            return out

        def unresolved(s):
            corr = (s.get("label_corrections") or {}) if isinstance(s, dict) else {}
            allowed = set(labels) | {str(v) for v in corr.values()}
            return used_labels(s) - allowed

        bad = unresolved(score)
        if not bad:
            return score
        logger.warning(
            "[plan] BT references unknown labels %s (valid: %s); "
            "re-prompting once with the exact set",
            sorted(bad),
            sorted(labels),
        )
        retry_instruction = (
            f"{instruction}\n\nIMPORTANT: your previous plan referenced "
            f"labels {sorted(bad)} which DO NOT EXIST in this scene. The "
            f"only valid keypoint labels are exactly: {sorted(labels)}. "
            f"Rewrite the plan using ONLY these labels. If a detection is "
            f"visually mislabeled you may rename it via label_corrections, "
            f"then use the corrected name."
        )
        score2 = self._planner.generate_score(
            instruction=retry_instruction,
            annotated_image=scene_image,
            scene_camera=scene_camera,
            keypoint_labels=labels,
            detection_details=detection_details,
            fewshot_examples=fewshot,
            robointer_context=robointer_context,
            robointer_strict=robointer_strict,
        )
        bad2 = unresolved(score2)
        if bad2:
            raise ValueError(
                f"Gemini plan references labels {sorted(bad2)} that are not "
                f"in the detections {sorted(labels)} even after a corrective "
                f"retry; refusing to execute an unresolvable plan."
            )
        logger.info("[plan] corrective re-prompt resolved the labels")
        return score2

    def execute(self, score: Dict, detections: List[ObjectDetection]) -> List[ExecutionResult]:
        """
        Execute a SPARK score on the robot.
        """
        if self._executor is None:
            logger.warning("No robot connected; cannot execute")
            return []

        # Clear the previous run's verdict, gates and release witness. The
        # executor outlives a task, so without this a stale `pass` from the
        # last run would be read as this run's success.
        success_verifier.reset_run_state(self._executor)

        # Apply Gemini label corrections to detections before building map.
        #
        # This pop is why a cached score must be hashed AFTER execution:
        # label_corrections is per-run bookkeeping that RENAMES live
        # detections, so replaying it blind in a different scene renames the
        # wrong object. bt_library strips the key before hashing, and
        # _maybe_save_bt stores the post-pop score, so the served hash and
        # the stored hash agree.
        corrections = score.pop("label_corrections", None) or {}
        if corrections:
            logger.info("Applying %d label correction(s) from Gemini:", len(corrections))
            correction_map = {str(k): str(v) for k, v in corrections.items()}
            for det in detections:
                if det.label in correction_map:
                    new_label = correction_map[det.label]
                    logger.info("  %s -> %s", det.label, new_label)
                    det.label = new_label

        # Label-drift tolerant map: a cached BT that says "blue block 2" or
        # "grey block" still binds when this run's SAM3 pass produced
        # "blue block" / "gray block". Exact hits behave identically to a
        # plain dict; see bt_label_resolver.
        detection_map = LabelResolvingDetectionMap()
        for det in detections:
            if det.position_3d is not None:
                detection_map[det.label] = {
                    "position_3d": (
                        det.position_3d.tolist()
                        if isinstance(det.position_3d, np.ndarray)
                        else det.position_3d
                    ),
                    "confidence": det.confidence,
                    "orientation_angle": det.orientation_angle,
                    "aspect_ratio": det.aspect_ratio,
                    # OBB short-axis length in METERS. Powers the
                    # mask-derived grasp-width prior in score_executor so
                    # the executor can synthesize a target_width for
                    # objects with no per-label calibration. 0.0 means no
                    # depth available, so the executor falls back to default.
                    "obb_minor_m": float(getattr(det, "obb_minor_m", 0.0) or 0.0),
                    # True when the mask still trips a quality trigger after
                    # reprompting. Forces the `auto` grasp strategy top-down.
                    "low_quality": bool(getattr(det, "low_quality", False)),
                    "reprompt_attempts": int(getattr(det, "reprompt_attempts", 0) or 0),
                    # Slot detection fields, populated by
                    # _enrich_with_slots for container labels (tray,
                    # plate, dish, bowl, drawer, dustpan). place_in_slot
                    # reads these to compute slot pose + gripper yaw.
                    "world_major_axis_rad": (
                        float(getattr(det, "world_major_axis_rad", None))
                        if getattr(det, "world_major_axis_rad", None) is not None
                        else None
                    ),
                    "slots": (
                        [
                            {
                                **s,
                                "world_xyz": (
                                    s["world_xyz"].tolist()
                                    if isinstance(s.get("world_xyz"), np.ndarray)
                                    else s.get("world_xyz")
                                ),
                            }
                            for s in (getattr(det, "slots", None) or [])
                        ]
                        if getattr(det, "slots", None)
                        else None
                    ),
                    "_mask": det.mask,
                    "_camera": getattr(det, "camera", None),
                }
                # Detector-fusion stamps (fused_confidence, axis_trust). Same
                # emit-only-when-measured convention as obb_confidence below;
                # detection_fusion.fusion_map_fields owns the key names.
                detection_map[det.label].update(fusion_map_fields(det))
                # How trustworthy the OBB axes are. Emitted ONLY when actually
                # measured: the grasp resolver treats an ABSENT key as unknown
                # and a PRESENT low value as a veto, so publishing a default
                # 0.0 for depth-less detections would kill every oriented grasp.
                _obb_conf = float(getattr(det, "obb_confidence", 0.0) or 0.0)
                if _obb_conf > 0.0:
                    detection_map[det.label]["obb_confidence"] = _obb_conf
                # Colour-free role names published by the task prompt
                # registry (e.g. "same color block 1"). Registered as
                # aliases rather than as extra dict entries so the
                # destination filter and the obstacle push still enumerate
                # only real detections. Without this a cached BT that
                # addresses a role cannot resolve it at all.
                detection_map.register_aliases(
                    getattr(det, "role_labels", None), det.label
                )

        # RoboInter (default OFF): the planner's spatial annotations, lifted
        # into the base frame and published onto the SAME entries above. Both
        # keys are BOUNDED, XY-only corrections to a measured detection -- a
        # proposal further than the cap is refused and perception wins -- and
        # neither exists at all when the extension is off.
        self._last_robointer = robointer_gate.apply_to_detection_map(
            self.robointer_config(), score, detections, detection_map, self
        )

        # Container-as-destination filter:
        # If the score sends grasped items INTO a container (the
        # container shows up as a move_to_keypoint AFTER a grasp), then
        # any other detections that overlap the container's XY footprint
        # are already-placed items and should be dropped from grasp
        # targets. For OUT-OF-container tasks (no grasp-to-container flow),
        # we keep all detections so the user can grasp items inside.
        destination_labels = set()
        try:
            # Flatten the score (handles nested sequence trees and flat
            # action lists) so container/receptacle targets are found
            # regardless of how the planner nested them.
            actions = self._flatten_score_actions(score)
            seen_grasp = False
            for act in actions:
                atype = act.get("type", "") if isinstance(act, dict) else ""
                params = act.get("params", {}) if isinstance(act, dict) else {}
                # Explicit container/receptacle params on any primitive
                # (place_in_slot container_label, sweep/pour target_label,
                # bimanual dustpan_label) are always destinations.
                for key in ("container_label", "target_label", "dustpan_label"):
                    lbl = params.get(key)
                    if lbl:
                        destination_labels.add(lbl)
                if atype.startswith("grasp") or atype == "pick":
                    seen_grasp = True
                elif atype == "move_to_keypoint" and seen_grasp:
                    kp = params.get("keypoint_label")
                    if kp:
                        destination_labels.add(kp)
                elif atype in ("release", "drop", "place"):
                    seen_grasp = False
        except Exception as _e:
            logger.debug("destination-label scan skipped: %s", _e)

        # Labels the plan itself references must NEVER be filtered: a
        # mug's own handle sits inside the mug's footprint, so a put-back
        # move_to_keypoint that makes the mug a destination would otherwise
        # drop 'mug handle' as already-placed cargo and kill the grasp.
        referenced_labels = set()
        try:
            for act in self._flatten_score_actions(score):
                params = act.get("params", {}) if isinstance(act, dict) else {}
                for key in (
                    "keypoint_label",
                    "container_label",
                    "target_label",
                    "source_label",
                    "dustpan_label",
                ):
                    lbl = params.get(key)
                    if lbl:
                        referenced_labels.add(str(lbl))
                for lbl in str(params.get("object_labels", "") or "").split(","):
                    if lbl.strip():
                        referenced_labels.add(lbl.strip())
            # A predicate's subject must survive the destination filter too:
            # filtering it away leaves the verifier with nothing to detect.
            referenced_labels |= verify_block_labels(score)
        except Exception:
            pass

        for dest_label in destination_labels:
            dest_det = detection_map.get(dest_label)
            if dest_det is None or dest_det.get("position_3d") is None:
                continue
            dest_pos = np.asarray(dest_det["position_3d"], dtype=float)
            dest_minor = float(dest_det.get("obb_minor_m") or 0.0)
            dest_radius = max(0.12, dest_minor * 0.6)
            to_drop = []
            for label, det in detection_map.items():
                if label == dest_label or label in referenced_labels:
                    continue
                pos = det.get("position_3d")
                if pos is None:
                    continue
                d_xy = float(np.linalg.norm(np.asarray(pos[:2], dtype=float) - dest_pos[:2]))
                if d_xy < dest_radius:
                    to_drop.append((label, d_xy))
            for label, d_xy in to_drop:
                logger.info(
                    "Destination filter ('%s'): dropping %s " "(d_xy=%.3fm < dest_radius=%.3fm)",
                    dest_label,
                    label,
                    d_xy,
                    dest_radius,
                )
                detection_map.pop(label, None)

        # Hand the destination labels to the executor so that
        # execution-time re-detection can apply the same filter
        # (planner's filter only runs once, at plan time; without
        # this, re-detect after a place can find the just-placed
        # object and retarget the gripper back to the container).
        try:
            self._executor._destination_labels = set(destination_labels)
        except Exception:
            pass

        self._executor.update_detections(detection_map)
        # Push detected objects as obstacles into SafeRobot for path safety
        if isinstance(self._robot, SafeRobot):
            obstacles = []
            for label, det in detection_map.items():
                pos = det.get("position_3d")
                if pos is not None:
                    obstacles.append(
                        Obstacle(
                            position=np.array(pos),
                            radius=0.05,
                            timestamp=time.monotonic(),
                        )
                    )
            self._robot._obstacle_map.update(obstacles)
            logger.info("Pushed %d detection obstacles to SafeRobot", len(obstacles))
        try:
            results = self._executor.execute_score(score)
        finally:
            # Which cached-BT labels had to be re-bound to differently-named
            # detections this run. Surfaced in the run result so a silent
            # mis-binding is auditable after the fact.
            self._last_label_resolutions = dict(detection_map.resolutions)
            if self._last_label_resolutions:
                logger.info(
                    "label resolver re-bound %d cached label(s): %s",
                    len(self._last_label_resolutions),
                    self._last_label_resolutions,
                )
        return results

    @staticmethod
    def _flatten_score_actions(score) -> List[dict]:
        """
        Flatten a SPARK score (tree of sequences/leaves, or a flat
        actions/children list) into the ordered list of leaf actions.

        Used by the closed-loop destination scan; kept independent of the
        executor so it works in dry runs with no robot connected.
        """
        if not isinstance(score, dict):
            return []
        out: List[dict] = []

        def walk(node):
            if not isinstance(node, dict):
                return
            children = node.get("children")
            if children:
                for child in children:
                    walk(child)
            else:
                out.append(node)

        if score.get("actions"):
            for act in score["actions"]:
                walk(act)
        else:
            walk(score.get("tree", score))
        return out

    def _closed_loop_destinations(self, score) -> set:
        """
        Labels that act as a destination/receptacle in this score.

        Walks the flattened tree and collects container-like targets across
        every primitive that has one: a move_to_keypoint that follows a
        grasp (pick-place), place_in_slot's container_label, sweep / scrub /
        pour's target_label, and the bimanual place/sweep dustpan_label.
        These are where objects are meant to END UP, so the progress check
        treats an object sitting in one of them as handled.
        """
        dests = set()
        seen_grasp = False
        for act in self._flatten_score_actions(score):
            if not isinstance(act, dict):
                continue
            atype = act.get("type", act.get("name", ""))
            params = act.get("params", {}) or {}
            for key in ("container_label", "target_label", "dustpan_label"):
                lbl = params.get(key)
                if lbl:
                    dests.add(str(lbl))
            if atype.startswith("grasp") or atype == "pick":
                seen_grasp = True
            elif atype == "move_to_keypoint" and seen_grasp:
                kp = params.get("keypoint_label")
                if kp:
                    dests.add(str(kp))
            elif atype in ("release", "drop", "place"):
                seen_grasp = False
        return dests

    @staticmethod
    def _base_label(label) -> str:
        """
        Strip a trailing instance number ("fork 2" -> "fork") so a target
        re-detected with fresh numbering still matches the planner's label.
        """
        return re.sub(r"\s+\d+$", "", str(label)).strip()

    def evaluate_scene_progress(self, score, prompts, handled_labels=None, captures=None) -> Dict:
        """
        Re-perceive the scene and report which targets still need work.

        Generic across tasks: a "target" is any detected object whose label
        is not a destination (receptacle / dustpan / container). A target is
        HANDLED when it sits inside a destination zone or its base label is
        in handled_labels (the executor's placed set). Everything else is
        unhandled work the closed loop should keep acting on, for example a
        re-pick of a dropped fork, a re-sweep of an object that missed the
        dustpan, or a lift of an item that did not move. Newly perturbed
        objects (added utensil, swapped receptacle) appear here on their own
        because the detection is run fresh.

        Returns {"unhandled": [labels], "handled": [labels],
                 "destinations": [labels], "detections": [ObjectDetection]}.
        """
        handled_labels = set(handled_labels or set())
        if captures is None:
            captures = self.capture()
        empty = {"unhandled": [], "handled": [], "destinations": [], "detections": []}
        if not captures:
            return empty

        destinations = self._closed_loop_destinations(score)
        dest_base = {self._base_label(d) for d in destinations}
        dets = self.merge_detections(self.detect(captures, prompts, multi_instance=True))

        floor_r = float(getattr(self.config, "closed_loop_clear_radius_m", 0.12))
        zones = []
        for det in dets:
            if det.position_3d is None:
                continue
            if self._base_label(det.label) in dest_base:
                minor = float(getattr(det, "obb_minor_m", 0.0) or 0.0)
                zones.append(
                    (
                        np.asarray(det.position_3d[:2], dtype=float),
                        max(floor_r, minor * 0.6),
                    )
                )

        handled_base = {self._base_label(h) for h in handled_labels}
        handled, unhandled = [], []
        for det in dets:
            if self._base_label(det.label) in dest_base:
                continue  # the receptacle itself is not a target
            # Handled = executor placed-set OR physically inside a destination
            # zone. The zone test alone is too strict: zones are circles of
            # radius max(0.12, obb_minor*0.6) around the destination CENTROID,
            # so an item correctly placed near the end of an elongated tray
            # sits outside every zone and would be re-picked forever.
            is_handled = det.label in handled_labels or self._base_label(det.label) in handled_base
            if not is_handled and det.position_3d is not None:
                xy = np.asarray(det.position_3d[:2], dtype=float)
                for zc, zr in zones:
                    if float(np.linalg.norm(xy - zc)) < zr:
                        is_handled = True
                        break
            (handled if is_handled else unhandled).append(det.label)

        return {
            "unhandled": unhandled,
            "handled": handled,
            "destinations": sorted(destinations),
            "detections": dets,
        }
